INSERT INTO `locations` (code, description) 
    VALUES 
    ('AND', 'Andorra'),
    ('ARE', 'United Arab Emirates'),
    ('AFG', 'Afghanistan'),
    ('ATG', 'Antigua and Barbuda'),
    ('ALB', 'Albania'),
    ('ARM', 'Armenia'),
    ('AGO', 'Angola'),
    ('ARG', 'Argentina'),
    ('AUT', 'Austria'),
    ('AUS', 'Australia'),
    ('AZE', 'Azerbaijan'),
    ('BIH', 'Bosnia and Herzegovina'),
    ('BRB', 'Barbados'),
    ('BGD', 'Bangladesh'),
    ('BEL', 'Belgium'),
    ('BFA', 'Burkina Faso'),
    ('BGR', 'Bulgaria'),
    ('BHR', 'Bahrain'),
    ('BDI', 'Burundi'),
    ('BEN', 'Benin'),
    ('BRN', 'Brunei Darussalam'),
    ('BOL', 'Bolivia'),
    ('BRA', 'Brazil'),
    ('BHS', 'Bahamas'),
    ('BTN', 'Bhutan'),
    ('BWA', 'Botswana'),
    ('BLR', 'Belarus'),
    ('BLZ', 'Belize'),
    ('CAN', 'Canada'),
    ('COD', 'Democratic Republic of the Congo'),
    ('CAF', 'Central African Republic'),
    ('COG', 'Congo'),
    ('CHE', 'Switzerland'),
    ('CIV', "Côte d'Ivoire"),
    ('CHL', 'Chile'),
    ('CMR', 'Cameroon'),
    ('CHN', 'China'),
    ('COL', 'Colombia'),
    ('CRI', 'Costa Rica'),
    ('CUB', 'Cuba'),
    ('CPV', 'Cabo Verde'),
    ('CYP', 'Cyprus'),
    ('CZE', 'Czechia'),
    ('DEU', 'Germany'),
    ('DJI', 'Djibouti'),
    ('DNK', 'Denmark'),
    ('DMA', 'Dominica'),
    ('DOM', 'Dominican Republic'),
    ('DZA', 'Algeria'),
    ('ECU', 'Ecuador'),
    ('EST', 'Estonia'),
    ('EGY', 'Egypt'),
    ('ERI', 'Eritrea'),
    ('ERI', 'Eritrea'),
    ('ESP', 'Spain'),
    ('ETH', 'Ethiopia'),
    ('FIN', 'Finland'),
    ('FJI', 'Fiji'),
    ('FSM', 'Micronesia'),
    ('FRA', 'France'),
    ('GAB', 'Gabon'),
    ('GBR', 'United Kingdom'),
    ('GRD', 'Grenada'),
    ('GEO', 'Georgia'),
    ('GHA', 'Ghana'),
    ('GMB', 'Gambia'),
    ('GIN', 'Guinea'),
    ('GNQ', 'Equatorial Guinea'),
    ('GRC', 'Greece'),
    ('GTM', 'Guatemala'),
    ('GNB', 'Guinea-Bissau'),
    ('GUY', 'Guyana'),
    ('HND', 'Honduras'),
    ('HRV', 'Croatia'),
    ('HTI', 'Haiti'),
    ('HUN', 'Hungary'),
    ('IDN', 'Indonesia'),
    ('IRL', 'Ireland'),
    ('ISR', 'Israel'),
    ('IND', 'India'),
    ('IRQ', 'Iraq'),
    ('IRN', 'Iran'),
    ('ISL', 'Iceland'),
    ('ITA', 'Italy'),
    ('JAM', 'Jamaica'),
    ('JOR', 'Jordan'),
    ('JPN', 'Japan'),
    ('KEN', 'Kenya'),
    ('KGZ', 'Kyrgyzstan'),
    ('KHM', 'Cambodia'),
    ('KIR', 'Kiribati'),
    ('COM', 'Comoros'),
    ('KNA', 'Saint Kitts and Nevis'),
    ('PRK', "Democratic People's Republic of Korea"),
    ('KOR', 'Republic of Korea'),
    ('KWT', 'Kuwait'),
    ('KAZ', 'Kazakhstan'),
    ('LAO', "Lao People's Democratic Republic"),
    ('LBN', 'Lebanon'),
    ('LCA', 'Saint Lucia'),
    ('LIE', 'Liechtenstein'),
    ('LKA', 'Sri Lanka'),
    ('LBR', 'Liberia'),
    ('LSO', 'Lesotho'),
    ('LTU', 'Lithuania'),
    ('LUX', 'Luxembourg'),
    ('LVA', 'Latvia'),
    ('LBY', 'Libya'),
    ('MAR', 'Morocco'),
    ('MCO', 'Monaco'),
    ('MDA', 'Moldova'),
    ('MNE', 'Montenegro'),
    ('MDG', 'Madagascar'),
    ('MHL', 'Marshall Islands'),
    ('MKD', 'North Macedonia'),
    ('MLI', 'Mali'),
    ('MMR', 'Myanmar'),
    ('MNG', 'Mongolia'),
    ('MRT', 'Mauritania'),
    ('MLT', 'Malta'),
    ('MUS', 'Mauritius'),
    ('MDV', 'Maldives'),
    ('MWI', 'Malawi'),
    ('MEX', 'Mexico'),
    ('MYS', 'Malaysia'),
    ('MOZ', 'Mozambique'),
    ('NAM', 'Namibia'),
    ('NER', 'Niger'),
    ('NGA', 'Nigeria'),
    ('NIC', 'Nicaragua'),
    ('NLD', 'Netherlands'),
    ('NOR', 'Norway'),
    ('NPL', 'Nepal'),
    ('NRU', 'Nauru'),
    ('NZL', 'New Zealand'),
    ('OMN', 'Oman'),
    ('PAN', 'Panama'),
    ('PER', 'Peru'),
    ('PNG', 'Papua New Guinea'),
    ('PHL', 'Philippines'),
    ('PAK', 'Pakistan'),
    ('POL', 'Poland'),
    ('PRT', 'Portugal'),
    ('PLW', 'Palau'),
    ('PRY', 'Paraguay'),
    ('QAT', 'Qatar'),
    ('ROU', 'Romania'),
    ('SRB', 'Serbia'),
    ('RUS', 'Russian Federation'),
    ('RWA', 'Rwanda'),
    ('SAU', 'Saudi Arabia'),
    ('SLB', 'Solomon Islands'),
    ('SYC', 'Seychelles'),
    ('SDN', 'Sudan'),
    ('SWE', 'Sweden'),
    ('SGP', 'Singapore'),
    ('SVN', 'Slovenia'),
    ('SVK', 'Slovakia'),
    ('SLE', 'Sierra Leone'),
    ('SMR', 'San Marino'),
    ('SEN', 'Senegal'),
    ('SOM', 'Somalia'),
    ('SUR', 'Suriname'),
    ('SSD', 'South Sudan'),
    ('STP', 'Sao Tome and Principe'),
    ('SLV', 'El Salvador'),
    ('SYR', 'Syrian Arab Republic'),
    ('SWZ', 'Eswatini'),
    ('TCD', 'Chad'),
    ('TGO', 'Togo'),
    ('THA', 'Thailand'),
    ('TJK', 'Tajikistan'),
    ('TLS', 'Timor-Leste'),
    ('TKM', 'Turkmenistan'),
    ('TUN', 'Tunisia'),
    ('TON', 'Tonga'),
    ('TUR', 'Turkey'),
    ('TTO', 'Trinidad and Tobago'),
    ('TUV', 'Tuvalu'),
    ('TZA', 'Tanzania'),
    ('UKR', 'Ukraine'),
    ('UGA', 'Uganda'),
    ('USA', 'United States of America'),
    ('URY', 'Uruguay'),
    ('UZB', 'Uzbekistan'),
    ('VCT', 'Saint Vincent and the Grenadines'),
    ('VEN', 'Venezuela'),
    ('VNM', 'Viet Nam'),
    ('VUT', 'Vanuatu'),
    ('WSM', 'Samoa'),
    ('YEM', 'Yemen'),
    ('ZAF', 'South Africa'),
    ('ZMB', 'Zambia'),
    ('ZWE', 'Zimbabwe');